### ISSUE TITLE
actions.json error on importing

### ISSUE THREAD

**Issue by AtsushiNemoto** [OLSV-oss/OSSLicenseSimpleViewer#1]
I got this serror on importing.

![osslsv-error](https://user-images.githubusercontent.com/26451120/101462623-bf6aa800-397f-11eb-8487-6466079913d6.jpg)

It looks the error raised in this code.
```
'
' JSONテキスト->オブジェクト変換 Macro
'
Public Function ParseJson(text As String) As Object
    With CreateObject("ScriptControl")
        .Language = "JScript"
'        .AddCode "function EvalText(text) { var val = []; try { val = eval('(' + text + ')'); } catch(error) { } return val;};"
        .AddCode "function EvalText(text) { return eval('(' + text + ')'); }"
        Set ParseJson = .CodeObject.EvalText(text)
    End With
End Function
```

Any advice?

**Comment by AtsushiNemoto** [comment]
The error did not happen with 32-bit version of Excel.

**Comment by OLSV-oss** [comment]
Hi, thank you for your issue. Unfortunately we support only 32-bit Excel for now. We'd be glad to plan the future enhancement!!

**Comment by AtsushiNemoto** [comment]
OK, close this issue.
